blog/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _

app_name = 'blogs'

urlpatterns = [
    path('', views.MagazinesView.as_view(), name="magazines"),
    path('magazine/<int:pk>/', views.MagazineView.as_view(), name="magazine_details"),
    path('blog/<int:pk>/', views.BlogView.as_view(), name="blog_details"),
    path('author/<int:pk>/', views.AuthorView.as_view(), name="author_details"),
    path('create/author/', views.AuthorCreateView.as_view(), name="create_author"),
    path('author/<int:pk>/delete', views.DeleteAuthorView.as_view(), name="delete_author"),
    # path('test/', views.translation_view1),
    # path('page/<int:page>/', views.TranslationView2.as_view()),
    # path(_('test2/'), views.translation_view3),
    # path('difference/', views.gettext_and_gettext_lazy),
    # path('Localize/', views.LocalizationView.as_view()),
    # path('profit/', views.ProfitView.as_view()),
    # path('timezone/', views.set_timezone, name="set_timezone"),
    # path('middleware/', views.MyTestView.as_view()),
    # path('handle/', views.handel_middleware),
    # path('send/', views.MyEmailView.as_view(), name="send_email"),
    # path('name/', views.NameView.as_view(), name="name"),
    path('contact/', views.ContactView.as_view(), name="contact_us"),
    path('manage/', views.manage_articles),
]

magazine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog
from django.views.decorators.cache import cache_page
from django import get_version

urlpatterns = [
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blogs')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms
from .models import *
from django.utils.translation import gettext_lazy as _
from django.utils.translation import ngettext_lazy
from django.forms import formset_factory


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = '__all__'

    profile_image = forms.ImageField(widget=forms.FileInput, label=_("Profile Image"))

    def clean_bio(self):
        message = _("too short")
        bio = self.cleaned_data["bio"]
        if len(bio) > 5:
            return bio
        else:
            raise forms.ValidationError(message)

    def clean_bio_ar(self):
        message = _("too short")
        bio_ar = self.cleaned_data["bio_ar"]
        if len(bio_ar) > 5:
            return bio_ar
        else:
            raise forms.ValidationError(message)

    def clean_name(self):
        message = _("This email address is already used.")
        name = self.cleaned_data['name']
        if Author.objects.filter(name=name).exists():
            raise forms.ValidationError(message)
        else:
            return name

    def clean_email(self):
        message = _("This email address is already used.")
        email = self.cleaned_data['email']
        if Author.objects.filter(email=email).exists():
            raise forms.ValidationError(message)
        else:
            return email


class MagazineForm(forms.ModelForm):
    class Meta:
        model = Magazine
        fields = '__all__'

    def clean_title(self):
        message = _("too short")
        title = self.cleaned_data["title"]
        if len(title) > 3:
            return title
        else:
            raise forms.ValidationError(message)

    def clean_title_ar(self):
        message = _("too short")
        title_ar = self.cleaned_data["title_ar"]
        if len(title_ar) > 3:
            return title_ar
        else:
            raise forms.ValidationError(message)

    def clean_description(self):
        message = _("too short")
        description = self.cleaned_data['description']
        if len(description) > 3:
            return description
        else:
            raise forms.ValidationError(message)

    def clean_description_ar(self):
        message = _("too short")
        description_ar = self.cleaned_data['description_ar']
        if len(description_ar) > 3:
            return description_ar
        else:
            raise forms.ValidationError(message)


MagazineFormset = formset_factory(MagazineForm, extra=1, can_delete=True)


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = '__all__'

    def clean_content(self):
        message = _("too short")
        content = self.cleaned_data['content']
        if len(content) > 10:
            return content
        else:
            raise forms.ValidationError(message)

    def clean_content_ar(self):
        message = _("too short")
        content_ar = self.cleaned_data['content_ar']
        if len(content_ar) > 10:
            return content_ar
        else:
            raise forms.ValidationError(message)


# another example
# class AuthorForm2(forms.ModelForm):
#     class Meta:
#         model = Author
#         fields = '__all__'
#     def clean_bio(self):
#         error_message = ngettext_lazy(
#             "%d letter, too short",
#             "%d letters, too short",
#         )
#         bio = self.cleaned_data["bio"]
#         if len(bio) > 5:
#             return bio
#         else:
#             raise forms.ValidationError(error_message % len(bio))

# class MyForm(forms.ModelForm):
#     class Meta:
#         model = Car
#         fields = ['date']
#         widgets = {
#             'my_date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}, localize=True),
#         }

# class ProfitForm(forms.Form):
#    storage = forms.IntegerField()
#    profit = forms.DecimalField(max_digits=4, decimal_places=2, localize=True)


# class NameForm(forms.Form):
#     your_name = forms.CharField(max_length=50, label=_("Enter your name"))
#

class EmailForm(forms.Form):
    subject = forms.CharField(required=True, label=_("Subject"))
    message = forms.CharField(widget=forms.Textarea, required=True, label=_("Message"))
    sender = forms.EmailField(required=True, label=_("Sender"))


EmailFormset = formset_factory(EmailForm, extra=2)


class ArticleForm(forms.Form):
    title = forms.CharField()
    pub_date = forms.DateField()

blog/views.py
from django.shortcuts import render
from .models import *
from django.views.generic import ListView, DetailView, TemplateView
from django.utils.translation import gettext as _, ngettext, gettext_lazy
from django.utils.text import format_lazy
from django.views import View
from django.http import HttpResponse
from django.utils.translation import pgettext
from django.utils.functional import lazy
from django.utils.safestring import mark_safe
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from django.shortcuts import redirect, render
import pytz
from .forms import *
from django.core.mail import BadHeaderError, send_mail, EmailMessage, EmailMultiAlternatives
from django.core import mail
from django.views.generic.edit import CreateView, FormView, DeleteView
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
import os
from django.forms import formset_factory


class MagazinesView(ListView):
    template_name = "blog/homepage.html"
    # queryset = Magazine.magazines.all()
    queryset = Magazine.objects.magazines()
    context_object_name = "magazines"

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     extra_data = self.request.extra_data
    #     context['extra_data'] = extra_data
    #     return context


class MagazineView(DetailView):
    model = Magazine
    template_name = "blog/magazine_details.html"
    context_object_name = "magazine"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # blogs = Blog.objects.filter(magazine_id=self.kwargs['pk'], status="p").order_by("-publish_date")
        blogs = Blog.objects.published_magazines(magazine=self.kwargs['pk'])
        context["blogs"] = blogs
        return context


class BlogView(DetailView):
    model = Blog
    template_name = "blog/blog_details.html"
    context_object_name = "blog"


class AuthorView(DetailView):
    template_name = "blog/author.html"
    context_object_name = "author"
    model = Author

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author = self.get_object()
        blogs = Blog.objects.author_blogs(author=author)
        context["blogs"] = blogs
        return context


# def translation_view1(request):
#     # may have several meaning, so we can define its meaning
#     month = pgettext("month name", "May")
#     # npgettext() with plural
#     output = _("Hello world, We are in %(month)s") % {'month': month}
#     return HttpResponse(output)


# class TranslationView2(View):
#     def get(self, request, page):
#         pluralization = ngettext(
#             "I'm in page %(page)d",
#             "I'm in pages %(page)d",
#             page,
#         ) % {
#                             'page': page,
#                         }
#         return HttpResponse(pluralization)
#
#
# mark_safe_lazy = lazy(mark_safe, str)


# def translation_view3(request):
#     # name = gettext_lazy('Khaled')
#     name = _('Khaled')
#     age = _("20 years old")
#     # result = format_lazy('{name}: {age} years old', name=name, age=age)
#     result = "%(name)s %(age)s" % {"name": name, "age": age}
#     test = mark_safe_lazy(_("<p>programmer</p>"))
#     return render(request, "blog/translation_template1.html", {
#         "result": result,
#         "test": test})


# def gettext_and_gettext_lazy(request):
#     name = gettext_lazy('Khaled ')
#     age = _("20 years old")
#     return render(request, "blog/translation_template2.html", {
#         "name": name,
#         "age": age
#     })
#
#
# class LocalizationView(View):
#     def get(self, request):
#         car = Car.objects.get(pk=1)
#         return render(request, "blog/localization.html", {"car": car})
#
# class ProfitView(FormView):
#     form_class = ProfitForm
#     template_name = "blog/profit.html"
#     success_url = reverse_lazy('blogs:magazines')
#     def form_valid(self, form):
#         storage = form.cleaned_data['storage']
#         profit = form.cleaned_data['profit']
#         person = Person.objects.get(pk=1)
#         Car.objects.create(person=person, storage=storage, profit=profit)
#         return super().form_valid(form)
#
#
# def set_timezone(request):
#     if request.method == 'POST':
#         request.session['django_timezone'] = request.POST['timezone']
#         return redirect('/')
#     else:
#         return render(request, 'blog/time_zone_template.html', {'timezones': pytz.common_timezones})


# class MyTestView(TemplateView):
#     template_name = 'my_template.html'

# def handel_middleware(request):
#     return HttpResponse(fd)

# send_mail(
#     'sport',
#     "it's sport message.",
#     'kkhhaa2002yl@gmail.com',
#     ['khalod.zeko@gmail.com'],
#     fail_silently=False,
# )

# I used locmem to testing environments not send a real email
# it will store in memory
# mail.send_mail(
#     'sport',
#     "it's sport message.",
#     'kkhhaa2002yl@gmail.com',
#     ['khalod.zeko@gmail.com'],
#     fail_silently=False,
# )
# emails = mail.outbox
# # emails have list of e email messages

# dummy like locmem, doesn't send a real message + doesn't store it in memory
# mail.send_mail(
#     'Subject here',
#     'Here is the message.',
#     'from@example.com',
#     ['to@example.com'],
#     fail_silently=False,
# )


# message1 = ('Family', 'Family is whole life', 'kkhhaa2002yl@gmail.com',
#             ['khalod.zeko@gmail.com', 'khalod.zeko22@gmail.com'])
# message2 = ('Sport', 'Sport is useful', 'kkhhaa2002yl@gmail.com', ['khalod.alshami@gmail.com'])
# send_mass_mail((message1, message2), fail_silently=False)

# class MyEmailView(View):
#     template_name = 'send_email.html'
#
#     def get(self, request, *args, **kwargs):
#         return render(request, self.template_name)
#
#     def post(self, request, *args, **kwargs):
#         subject = request.POST.get('subject', '')
#         message = request.POST.get('message', '')
#         to_email = request.POST.get('to_email', '')
#         if subject and message and to_email:
#             try:
#                 send_mail(subject, message, 'kkhhaa2002yl@gmail.com', [to_email])
#             except BadHeaderError:
#                 return HttpResponse('Invalid header found.')
#             return HttpResponseRedirect('/en/')
#         else:
#             return HttpResponse('Make sure all fields are entered and valid.')

# it has more options like reply_to, attach_file, attach
# email = EmailMessage(
#     'Good morning',
#     "I'm khaled",
#     'kkhhaa2002yl@gmail.com',
#     ['khalod.zeko@gmail.com', 'khalod.zeko22@gmail.com'],
#     ['khalod.alshami@gmail.com'],
#     reply_to=['khalod.zeko@gmail.com'],
#     headers={'Message-ID': 'kh775'},
# )
# email.attach_file('blog/static/images/khaled.jpeg')
# image_path = "blog/static/images/khaled.jpeg"
# with open(image_path, 'rb') as img:
#     image_data = img.read()
#     image_name = os.path.basename(image_path)
#     email.attach(image_name, image_data, 'image/jpeg')
# with open('blog/static/pdf/khaledPDF.pdf', 'rb') as pdf:
#     email.attach('khaledPDF.pdf', pdf.read(), 'application/pdf')
# email.send()


# To send a text and HTML combination message
# html = '<p>An <strong>important</strong> message from khaled</p>'
# msg = EmailMultiAlternatives("Khaled", 'an Important message from khaled',
# "kkhhaa2002yl@gmail.com", ['khalod.zeko@gmail.com'])
# # msg.attach_alternative(html, "text/html")
# msg.send()


# email1 = EmailMessage(
#     'Good morning',
#     "I'm khaled",
#     'kkhhaa2002yl@gmail.com',
#     ['khalod.zeko@gmail.com', 'khalod.zeko22@gmail.com'],
#     headers={'Message-ID': 'kh775'},
# )
# email2 = EmailMessage(
#     'Good morning',
#     "I'm khaled",
#     'kkhhaa2002yl@gmail.com',
#     ['khalod.zeko@gmail.com', 'khalod.zeko22@gmail.com'],
#     headers={'Message-ID': 'kh775'},
# )
# email3 = EmailMessage(
#     'Good morning',
#     "I'm khaled",
#     'kkhhaa2002yl@gmail.com',
#     ['khalod.zeko@gmail.com', 'khalod.zeko22@gmail.com'],
#     headers={'Message-ID': 'kh775'},
# )
#
# # by this way, we will send multiple EmailMessage
# emails = [email1, email2, email3]
# connection = mail.get_connection()
# messages = emails
# connection.send_messages(messages)

# class NameView(FormView):
#     template_name = 'name_template.html'
#     form_class = NameForm
#     success_url = reverse_lazy('blogs:magazines')
#
#     def form_valid(self, form):
#         print(form.cleaned_data['your_name'])
#         return super().form_valid(form)
#
#     def form_invalid(self, form):
#         messages.error(self.request, 'Please correct the errors below.')
#         return super().form_invalid(form)

class ContactView(FormView):
    template_name = "blog/email.html"
    form_class = EmailForm
    success_url = reverse_lazy('blogs:magazines')

    def form_valid(self, form):
        subject = form.cleaned_data['subject']
        message = form.cleaned_data['message']
        sender = form.cleaned_data['sender']
        send_mail(subject, message, sender, ['kkhhaa2002yl@gmail.com'])
        return super().form_valid(form)


def manage_articles(request):
    ArticleFormset = formset_factory(ArticleForm, extra=2, can_delete=True)
    if request.method == 'POST':
        formset = ArticleFormset(request.POST, request.FILES, prefix='articles')
        if formset.is_valid():
            for form in formset:
                print(form.cleaned_data.get('DELETE'))
    else:
        formset = ArticleFormset(prefix='articles')
    return render(request, 'blog/manage.html', {'formset': formset})


class AuthorCreateView(FormView):
    form_class = AuthorForm
    template_name = "blog/create/create_author.html"
    success_url = reverse_lazy('blogs:magazines')

    def form_valid(self, form):
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']

blog/templates/blog/author.html
{% include "blog/base.html" %}
{% load i18n %}

{% block content %}
    <div>
        <h3>{% trans "Name: " %} {{ author.name }}</h3>
        <p>{% trans "Email: " %} {{ author.email }}</p>
        <p>{{ author.get_bio }}</p>
        <img width="300px" src="{{ author.profile_image.url }}">
        <br>
        <form method="post" action="{% url 'blogs:delete_author' author.pk %}">
            {% csrf_token %}
            <button type="submit">{% trans "Delete" %}</button>
            <a href="{% url 'blogs:create_author' %}"><h4>{% trans "Create Author" %}</h4></a>
        </form>
    </div>
    <br>
    <br>
    <br>
    {% if blogs %}
        {{ blogs|length }} {% trans "Blog" %}{{ blogs|length|pluralize }}:
        <br/>
        <br/>
        <br/>
        <br/>
        {% for blog in blogs %}
            <div>
                <a href="{{ blog.get_absolute_url }}"><h4>{% trans "Title: " %} {{ blog.get_title }}</h4></a>
            </div>
            <br/>
            <br/>
        {% endfor %}
    {% else %}
        <p>{% trans "0 Blogs" %}</p>
    {% endif %}
{% endblock %}

blog/templates/blog/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% trans "Khaled" %}</title>
</head>
<body>
    <div class="header">
        <h1>{% trans "Khaled Site" %}</h1>
        <div>
            <h3><a href="{% url 'blogs:magazines' %}">{% trans "Magazines" %}</a></h3>
            <h3><a href="{% url 'blogs:contact_us' %}">{% trans "Contact us" %}</a></h3>
        </div>
    </div>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block content %}{% endblock %}
</body>
</html>

blog/templates/blog/blog_details.html
{% include "blog/base.html" %}
{% load i18n %}

{% block content %}
<div>
    <div>
        <img width="300px" src="{{ blog.cover_image.url }}">
    </div>
    <div>
        <h4>{% trans "Magazine: " %} {{ blog.magazine }}</h4>
        <a href="{{ blog.author.get_absolute_url }}"><h4>{% trans "Author: " %} {{ blog.author.name|upper }}</h4></a>
        <h4>{% trans "Title: " %}{{ blog.get_title }}</h4>
        <h4>{% trans "Created on: " %} {{ blog.publish_date|date:'F j, Y' }} {% trans "at" %} {{ blog.publish_date|time:'g:i A' }}</h4>
    </div>
    <div>
        <p>{{ blog.get_content }}</p>
    </div>
</div>
{% endblock %}

blog/templates/blog/email.html
{% include "blog/base.html" %}
{% load i18n %}
{% block content %}
    <br>
    <h4>Contact us</h4>
    <form method="POST" action="{% url 'blogs:contact_us' %}">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in form %}
            <div>
                {% if field.errors %}
                    <ol>
                        {% for error in field.errors %}
                            <li><strong>{{ error|escape }}</strong></li>
                        {% endfor %}
                    </ol>
                {% endif %}
                {{ field.legend_tag }} {{ field }}
            </div>
            <br>
        {% endfor %}
        <button type="submit">Send</button>
    </form>
{% endblock %}

blog/templates/blog/homepage.html
{% include "blog/base.html" %}
{% load i18n %}

{% block content %}
    {{ extra_data.test }}
    {% for magazine in magazines %}
        <div>
            <hr>
            <br>
            <a href="{{ magazine.get_absolute_url }}">
                <p>{{ magazine.get_title }}</p>
            </a>
            <a href="{{ magazine.get_absolute_url }}">
                <p>{% trans "description: " %} {{ magazine.get_description|truncatechars:20 }}</p>
            </a>
            <br>
            <hr>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/magazine_details.html
{% include "blog/base.html" %}
{% load i18n %}

{% block content %}
    <div>
        <h3>{{ magazine.get_title|capfirst }}</h3>
        <p>{{ magazine.get_description }}</p>
        <p>
            {% trans "Created on " %} {{ magazine.publish_date|date:'F j, Y' }}
            {% trans "at" %} {{ magazine.publish_date|time:'g:i A' }}
        </p>
    </div>
    <br>
    <br>
    <br>
    {% if blogs %}
        {{ blogs|length }} {% trans "Blog" %} {{ blogs|length|pluralize }}:
        <br/>
        <br/>
        <br/>
        <br/>
        {% for blog in blogs %}
            <div>
                <a href="{{ blog.get_absolute_url }}">
                    <img width="222px" src="{{ blog.cover_image.url }}">
                </a>
                <p>{% trans "Author: " %} {{ blog.author.name }}</p>
                <h4>{% trans "Title: " %} {{ blog.get_title }}</h4>
            </div>
            <br/>
            <br/>
            <br/>
            <br/>
        {% endfor %}
    {% else %}
        <h3>{% trans "0 blogs... No blogs to display" %}</h3>
    {% endif %}
{% endblock %}

blog/templates/blog/manage.html
<form method="POST">
    {% csrf_token %}
    {{ formset.management_form }}
    <table>
        {% for form in formset %}
            {{ form }}
        {% endfor %}
    </table>
    <button type="submit">Done</button>
</form>

{#<form method="post">#}
{#    <table>#}
{#        {{ formset }}#}
{#    </table>#}
{#</form>#}

blog/templates/blog/profit.html
{% load l10n %}
{% load humanize %}

{% localize on %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endlocalize %}

{% localize off %}
    {{ value|localize }}
{% endlocalize %}