blog/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _

app_name = 'blogs'

urlpatterns = [
    path('', views.MagazinesView.as_view(), name="magazines"),
    path('magazine/<int:pk>/', views.MagazineView.as_view(), name="magazine_details"),
    path('blog/<int:pk>/', views.BlogView.as_view(), name="blog_details"),
    path('author/<int:pk>/', views.AuthorView.as_view(), name="author_details"),
    path('create/author/', views.AuthorCreateView.as_view(), name="create_author"),
    path('author/<int:pk>/delete', views.DeleteAuthorView.as_view(), name="delete_author"),
    # path('test/', views.translation_view1),
    # path('page/<int:page>/', views.TranslationView2.as_view()),
    # path(_('test2/'), views.translation_view3),
    # path('difference/', views.gettext_and_gettext_lazy),
    # path('Localize/', views.LocalizationView.as_view()),
    # path('profit/', views.ProfitView.as_view()),
    # path('timezone/', views.set_timezone, name="set_timezone"),
    # path('middleware/', views.MyTestView.as_view()),
    # path('handle/', views.handel_middleware),
    # path('send/', views.MyEmailView.as_view(), name="send_email"),
    # path('name/', views.NameView.as_view(), name="name"),
    path('contact/', views.ContactView.as_view(), name="contact_us"),
    path('manage/', views.manage_articles),
]

magazine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog
from django.views.decorators.cache import cache_page
from django import get_version

urlpatterns = [
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blogs')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Khaled</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <div class="header">
        <h1>Khaled Site</h1>
        <div>
            <h3><a href="{% url 'blogs:magazines' %}">Magazines</a></h3>
        </div>
    </div>
    {% block content %}{% endblock %}
</body>
</html>

templates/email.html
{% include "blog/base.html" %}
{% load i18n %}
{% block content %}
    <br>
    <h4>Contact us</h4>
    <form method="POST" action="{% url 'blogs:contact_us' %}">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in form %}
            <div>
                {% if field.errors %}
                    <ol>
                    {% for error in field.errors %}
                        <li><strong>{{ error|escape }}</strong></li>
                    {% endfor %}
                    </ol>
                {% endif %}
                {{ field.legend_tag }} {{ field }}
            </div>
            <br>
        {% endfor %}
        <button type="submit">Send</button>
    </form>
{% endblock %}

templates/homepage.html
{% include "base.html" %}

{% block content %}
    {% for magazine in magazines %}
        <div>
            <hr>
            <br>
            <a href="{{ magazine.get_absolute_url }}">
                <p>{{ magazine.title|capfirst }}</p>
            </a>
            <a href="{{ magazine.get_absolute_url }}">
                <p>description: {{ magazine.description|truncatechars:20 }}</p>
            </a>
            <br>
            <hr>
        </div>
    {% endfor %}
{% endblock %}

templates/my_template.html
{{ custom_header }}
{{ my_data }}

templates/name_template.html
<form method="POST" action="{% url 'blogs:name' %}">
    {% csrf_token %}
    {{ form.as_div }}
    <button type="submit">Send</button>
</form>

templates/send_email.html
<h1>Send Email</h1>
<form method="POST" action="{% url 'blogs:send_email' %}">
    {% csrf_token %}
    <label for="to_email">To:</label>
    <input type="email" id="to_email" name="to_email" required>
    <br>
    <label for="subject">Subject:</label>
    <input type="text" id="subject" name="subject" required>
    <br>
    <label for="message">Message:</label>
    <textarea id="message" name="message" required></textarea>
    <br>
    <button type="submit">Send</button>
</form>